// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWechat = "wechat"

// Wechat mapped from table <wechat>
type Wechat struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Aid           string    `gorm:"column:aid" json:"aid"`
	CreateTime    int64     `gorm:"column:create_time;comment:原本的发表时间" json:"create_time"`
	Link          string    `gorm:"column:link;comment:地址" json:"link"`
	Title         string    `gorm:"column:title;comment:标题" json:"title"`
	CreateTimeTr  time.Time `gorm:"column:create_time_tr;comment:日期格式的发表时间" json:"create_time_tr"`
	CreateTimeStr string    `gorm:"column:create_time_str;comment:日期字符串格式" json:"create_time_str"`
}

// TableName Wechat's table name
func (*Wechat) TableName() string {
	return TableNameWechat
}
